src/main.rs
src/types.rs

Bit ugly still since this is exploration phase but it appears to work!

Committers per repo

---

src/gha_sources.rs
src/lib.rs
src/main.rs
src/types.rs

Still not quite right, I need to take another look at it.

First pass at splitting into modules.

---

Cargo.toml

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/6 .

Use new release of Rusoto.

---

src/gha_sources.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/12 .

Page S3 results.

---

src/gha_sources.rs
src/main.rs
src/types.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/20 .

Retry S3 download if it didn't go well.

---

.gitignore
src/main.rs
src/types.rs

Next step: toss it into a database instead of to disk.

Write out sql

---

src/gha_sources.rs
src/main.rs
src/types.rs

Addresses some cases of https://github.com/matthewkmayer/rusty-von-humboldt/issues/22 .

Handle some cases of malformed data.

---

src/gha_sources.rs
src/main.rs
src/types.rs

Trimming for only repo

---

src/gha_sources.rs
src/main.rs

Much more performant, but more to go.

Use dem channels

---

Cargo.toml
src/main.rs
src/types.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/47 .

Option for obfuscating committer IDs.

---

src/main.rs

Fixes last bit of https://github.com/matthewkmayer/rusty-von-humboldt/issues/44 .

WIP for group inserting committers.

---

src/main.rs

turn on obsfucaction

---

Cargo.toml
README.md
src/gha_sources.rs
src/lib.rs
src/main.rs
src/types.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/38 .

Switch most things to use a logger

---

README.md

Made the logging portion of README more accurate and helpful.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/main.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/74 .

Use crossbeam channels.

---

CHANGELOG.md
README.md
src/main.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/75 .

Use env vars to switch modes.

---

CHANGELOG.md
src/gha_sources.rs
src/main.rs

Addresses https://github.com/matthewkmayer/rusty-von-humboldt/issues/92 .
```
Welcome to Rusty von Humboldt.
Environment Check is complete.
Completed 41 hours of GHA in 187 seconds
This is Rusty von Humboldt, heading home.
```

Print time taken and cargo fmt it.

---

CHANGELOG.md
Cargo.toml

Bump the version number.

---

CHANGELOG.md
src/main.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/94 .

Swapping Vector out for BTreeMap.

---

CHANGELOG.md
src/main.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/108 .

Check destination bucket access early.

---

src/main.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/106 .

Log if channel is full.

---

src/gha_sources.rs
src/main.rs

Fixes https://github.com/matthewkmayer/rusty-von-humboldt/issues/40 enough for now. 🤠

Better error handling and some retry logic.
